### PR TITLE
fix code to work again

### PR DESCRIPTION
**Pull request by WilliamAnimate**
... at least works again on webkit2gtk ig

### CODE REVIEW

**Comment by XandrCopyrighted** [comment]
sucks to be u, no free pr :>

**Comment by XandrCopyrighted** [comment]
I'll change cargo.toml, reason why I made js into it's own folder is cuz I wanna separate everything

**Comment by XandrCopyrighted** [comment]
> this isn't how tauri works

It did compile, so idk

**Comment by WilliamAnimate** [comment]
> > this isn't how tauri works
> 
> It did compile, so idk

its not a problem on compiling, its tauri not working post-compilation

we call em bugs

**Comment by WilliamAnimate** [comment]
@XandrCopyrighted now that you find out that the code doesn't work, how about you merge this pr

**Comment by XandrCopyrighted** [comment]
i swear it was working when I tested it, ugh fine

**Comment by WilliamAnimate** [comment]
> i swear it was working when I tested it, ugh fine

browser != tauri

how i assume tauri works (so take this with a grain of salt) is that it launches its own webserver on localhost, that `cargo tauri dev` only has the folders from where it thinks the **ENTIRE** frontend is.

so it should be trivial that if it doesn't work here, it won't work when compiled.

**Comment by XandrCopyrighted** [comment]
> i swear it was working when I tested it

must be a skill issue

**Comment by XandrCopyrighted** [comment]
> browser != tauri

ah.

**Comment by XandrCopyrighted** [comment]
https://github.com/XandrCopyrighted/Cazic/actions

**Comment by XandrCopyrighted** [comment]
> sucks to be u, no free pr :>

you did got a free pr at the end.

**Comment by WilliamAnimate** [comment]
> > sucks to be u, no free pr :>
> 
> you did got a free pr at the end. wow lmao

its not a free pr, but one that benifits both of us.

if it weren't for me forking this repo (like i did to xfetch), you *probably* might have spent a bit of time trying to figure out why its not working

or not

who knows

¯\_(ツ)_/¯

**Pull request merged**
