### PR TITLE
Add discord rpc

### LINKED ISSUE #4: Discord RPC? Maybe?

### PR DESCRIPTION
**Pull request by WilliamAnimate**
title says it all.

closes #4

### CODE REVIEW

**Comment by XandrCopyrighted** [comment]
https://github.com/users/XandrCopyrighted/projects/2

it's planned

**Comment by WilliamAnimate** [comment]
im working on it you doofus

**Comment by XandrCopyrighted** [comment]
image

**Comment by WilliamAnimate** [comment]
bro wtf i didn't-

**Pull request merged**
